FROM quay.io/astronomer/astro-runtime-dev:11.0.0-alpha5

# ENV AIRFLOW__WEBSERVER__NAVBAR_COLOR="#fccb44"
# ENV AIRFLOW__WEBSERVER__NAVBAR_TEXT_COLOR="#58875b"

# new in 2.9
# ENV AIRFLOW__WEBSERVER__NAVBAR_HOVER_COLOR="#e63c3c"
# ENV AIRFLOW__WEBSERVER__NAVBAR_LOGO_TEXT_COLOR="#7a3ce6"